megaport/megaportgo

- service/vxc/partner.go
- types/vxc_order.go
Fixes # (Not a bug fix)
Adding :
- Oracle as a partner 
- OCI VXC
**NOTE** If multiple authors have commited to this PR, each …
> Adding Oracle and OCI VXC

- .github/dependabot.yml
> adding dependabot configuration

- .github/workflows/test.yml
> start running tests on CI

- client.go
- client_test.go
- shared/utility.go
> Fixes linter issues

- authentication.go
- port.go
- product.go
Updates logs to use context when available and changes a few debug messages to warn where appropriate
> fix: logger context and updates log levels

- client.go
Adds request context for all requests
> fix: uses context when building requests

- .github/workflows/lint.yml
- .github/workflows/test.yml
- mcr.go
- mve_test.go
Fixes HTTP path in unit test that was causing test to fail
> fix: http path in MVE unit test

- .golangci.yml
Update golangci-lint config for sloglint - see: https://github.com/go-simpler/sloglint/pull/33
> Fix sloglint property

- .github/workflows/test.yml
Adds integration testing to actions
> ci: adds integration testing back to actions

- .github/workflows/test.yml
Removes integration test flag from unit tests
> fix: removes integration test flag from unit tests

- client.go
- port_integration_test.go
- service_keys.go
- service_keys_test.go
- vxc.go
- vxc_integration_test.go
- vxc_types.go
> feat: service key service, unit tests for service key, added integration tests in port and vxc service

- mve.go
- mve_test.go
- mve_types.go
> feat: mve image details and available mve sizes

- mcr.go
- mcr_types.go
- mve.go
- mve_types.go
- port.go
- port_types.go
- vxc.go
- vxc_types.go
> feat: promo code in resource orders

- mcr.go
- mcr_types.go
> fix: get prefix filter list id after creating mcr prefix filter list

- port_integration_test.go
- vxc_types.go
> fix: support for transit VXC

- vxc.go
- vxc_types.go
> fix: support for cost centre in vxc buy request

- mve.go
- mve_types.go
> fix: support cost_centre in both creating/updating MVE

- mcr.go
- mcr_integration_test.go
- mcr_types.go
> feat: Get Prefix Filter List (for entries), Modify Prefix Filter List, Delete Prefix Filter List

- vxc.go
- vxc_types.go
> feat: support bEndInnerVLAN in go SDK

- vxc_test.go
- vxc_types.go
Adds custom JSON Unmarshalling to handle issue with API response for VLL as `[]` instead of `{}`
> fix: adds custom JSON Unmarshaling for VLL issue on VXC

- vxc_types.go
> fix: add json field exclusion tag to partner config interface fields

- mcr.go
- mve.go
- port.go
- product.go
- vxc.go
> feat: validation for product and services

- mve.go
- mve_test.go
- mve_types.go
> fix: put mve diversity zone in nested config field for order

- mve_types.go
> fix: omit empty mveLabel in vendorConfig

- vxc_types.go
> fix: add missing field for amazonAsn in cspConnectionAWS struct

- vxc_types.go
> fix: added fields to csp connection for vrouter and azure

- mve.go
- mve_types.go
> fix: ssh public key for palo alto config

- vxc_types.go
> fix: update to correct JSON for Oracle VXC CSP Config, Correct JSON for Azure Peering Config

- mve.go
- mve_test.go
> cleanup: remove unnecessary switch case in createMVEOrder

- client.go
- errors.go
- managed_account.go
- managed_account_test.go
> feat: managed accounts service - create, list, get, update

- vxc_types.go
> feat: support IBM partner configuration in VXC service

- mcr.go
- mcr_integration_test.go
- mcr_types.go
- megaport_test.go
- mve.go
- mve_integration_test.go
- mve_types.go
- port.go
- port_integration_test.go
- port_types.go
- product.go
- product_test.go
- vxc.go
- vxc_integration_test.go
- vxc_types.go
> feat: support resource tags for megaport services

- vxc_types.go
> fix: add oracle csp connection to switch case for map

- vxc_types.go
> fix: make optional Azure Peering fields omitempty

- service_keys.go
> fix: add support in service key resource for both port uid and port id

- client.go
> fix: change staging oauth token url

- client.go
> fix: add mpone-dev environment and base url to mp client

- README.md
> cleanup: fix README file under agreement

- vxc_types.go
> fix: add localAsn to bgp connection config struct

- client.go
- ix.go
- ix_integration_test.go
- ix_test.go
- ix_types.go
This commit introduces the Internet Exchange (IX) service, enabling users to manage IX resources via the Megaport API.
Key changes include:
-   **IX Service Implementation:** Implements the `IXServiceOp` struct and associated methods for interacting with the IX endpoints.
-   **IX Data Types:** Defines data types for IX resources, requests, and responses, including `IX`, `BuyIXRequest`, `BuyIXResponse`, `UpdateIXRequest`, `DeleteIXRequest`, and related structures.
-   **API Endpoint Integration:** Integrates with the Megaport API endpoints for buying, retrieving, updating, and deleting IX resources.
-   **Unit Testing:** Adds unit tests for the IX service methods, ensuring proper functionality and error handling.
-   **Integration Testing:** Includes integration tests to validate the …
> feat: Implement Internet Exchange (IX) service

- product.go
> feat: GetProductType endpoint

- mcr.go
- mve.go
- mve_integration_test.go
- mve_types.go
- port.go
- product.go
- vxc_integration_test.go
> feat: add safeDelete functionality to port, mcr, mve resources

- mcr_types.go
> fix: add diversity zone field to mcr at root level

- mve_types.go
Addresses https://github.com/megaport/terraform-provider-megaport/issues/278
**NOTE** If multiple authors have …
> fix: make mve vendor config fields omit empty for improved flexibility
